### ISSUE TITLE
Cant see ticket

### ISSUE THREAD

**Issue by Danielss89** [hubot-archive/hubot-assembla#1]
Hi

I have a problem with this module. I'm trying to use "ticket #xxx" but get the following output in console(and nothing in flow):

```
[Mon Sep 29 2014 15:53:50 GMT+0200 (CEST)] ERROR SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /Users/Danielss89/Server/hubot/node_modules/hubot-assembla/src/assembla.coffee:64:17, <js>:36:31
  at IncomingMessage.<anonymous> (/Users/Danielss89/Server/hubot/node_modules/hubot/node_modules/scoped-http-client/lib/index.js:70:20)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:929:16
  at process._tickCallback (node.js:419:13)
```

**Comment by benwtr** [comment]
@Danielss89 I can't find anything wrong.

Be sure you're setting the required environment variables, including the name of an assembla workspace that has a ticket tool on it. You also need to register an application at https://www.assembla.com/user/edit/manage_clients

export HUBOT_ASSEMBLA_API_APP_ID='aYxECyt_qr5kpdacwqjQYw'
export HUBOT_ASSEMBLA_API_APP_SECRET='<redacted>'
export HUBOT_ASSEMBLA_SPACE='fdsafsd'

Quick test:

```
➜  foo  git clone git@github.com:github/hubot.git
Cloning into 'hubot'...
remote: Counting objects: 6005, done.
remote: Compressing objects: 100% (3221/3221), done.
remote: Total 6005 (delta 2655), reused 5971 (delta 2625)
Receiving objects: 100% (6005/6005), 1.47 MiB | 1.29 MiB/s, done.
Resolving deltas: 100% (2655/2655), done.
Checking connectivity... done.
➜  foo  cd hubot
➜  hubot git:(master) ✗ npm install
optparse@1.0.4 node_modules/optparse

log@1.4.0 node_modules/log

scoped-http-client@0.9.8 node_modules/scoped-http-client

coffee-script@1.6.3 node_modules/coffee-script

express@3.3.4 node_modules/express
├── methods@0.0.1
├── fresh@0.1.0
├── range-parser@0.0.4
├── cookie-signature@1.0.1
├── buffer-crc32@0.2.1
├── cookie@0.1.0
├── mkdirp@0.3.5
├── commander@1.2.0 (keypress@0.1.0)
├── send@0.1.3 (mime@1.2.11)
├── debug@2.0.0 (ms@0.6.2)
└── connect@2.8.4 (uid2@0.0.2, pause@0.0.1, qs@0.6.5, bytes@0.2.0, formidable@1.0.14)
➜  script git:(master) ✗ cd src/scripts
➜  src git:(master) ✗ cd scripts
➜  scripts git:(master) ✗ ls
events.coffee         httpd.coffee          pugme.coffee          storage.coffee
google-images.coffee  maps.coffee           roles.coffee          translate.coffee
help.coffee           ping.coffee           rules.coffee          youtube.coffee
➜  scripts git:(master) ✗ wget https://raw.githubusercontent.com/hubot-scripts/hubot-assembla/master/src/assembla.coffee

--2014-10-09 13:35:52--  https://raw.githubusercontent.com/hubot-scripts/hubot-assembla/master/src/assembla.coffee
Resolving raw.githubusercontent.com... 199.27.79.133
Connecting to raw.githubusercontent.com|199.27.79.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12551 (12K) [text/plain]
Saving to: 'assembla.coffee'

100%[==============================================================================>] 12,551      --.-K/s   in 0.002s

2014-10-09 13:35:53 (5.41 MB/s) - 'assembla.coffee' saved [12551/12551]

➜  scripts git:(master) ✗ cd ..
➜  src git:(master) ✗ cd ..
➜  hubot git:(master) ✗ export HUBOT_ASSEMBLA_API_APP_ID='aYxECyt_qr5kpdacwqjQYw'
➜  hubot git:(master) ✗ export HUBOT_ASSEMBLA_API_APP_SECRET='<redacted>'
➜  hubot git:(master) ✗ export HUBOT_ASSEMBLA_SPACE='fdsafsd'
➜  hubot git:(master) ✗ ./bin/hubot -d -n b
[Thu Oct 09 2014 13:40:20 GMT-0700 (PDT)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
[Thu Oct 09 2014 13:40:20 GMT-0700 (PDT)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
[Thu Oct 09 2014 13:40:20 GMT-0700 (PDT)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
[Thu Oct 09 2014 13:40:20 GMT-0700 (PDT)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
[Thu Oct 09 2014 13:40:20 GMT-0700 (PDT)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
[Thu Oct 09 2014 13:40:20 GMT-0700 (PDT)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
b> ticket #1
b> Looks like you need to authenticate. Please generate a PIN code here: https://api.assembla.com/authorization?client_id=aYxECyt_qr5kpdacwqjQYw&response_type=pin_code
b> Then, tell me your pin. "b assembla pin <your_pin_here>"
b> b assembla pin 2567835
b> Access token acquired and stored for user 1
b> ticket #1
b> Ticket #1, test ticket
https://www.assembla.com/spaces/fdsafsd/tickets/1
b>
```

**Comment by benwtr** [comment]
@Danielss89 Feel free to reopen and ask away if you're still having trouble. Would help to have steps to reproduce.
